/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import mappings.base.Player;
import mappings.humans.Mage;
import mappings.humans.Paladin;
import mappings.humans.Thief;
import mappings.humans.Warrior;

/**
 *
 * @author jonas
 */
public class HumanScreen extends javax.swing.JFrame {

    private Player player;
    
    HumanScreen(Player player) {
        initComponents();
        this.player = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paladin = new javax.swing.JButton();
        warrior = new javax.swing.JButton();
        mage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        thief = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Paladin.jpg"))); // NOI18N
        jLabel2.setLabelFor(paladin);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/warrior.jpg"))); // NOI18N
        jLabel1.setLabelFor(warrior);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mage.png"))); // NOI18N
        jLabel3.setLabelFor(mage);

        paladin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paladin.setText("Paladino");
        paladin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paladinActionPerformed(evt);
            }
        });

        warrior.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        warrior.setText("Guerreiro");
        warrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warriorActionPerformed(evt);
            }
        });

        mage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mage.setText("Mago");
        mage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mageActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Thief.jpg"))); // NOI18N
        jLabel4.setLabelFor(thief);

        thief.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thief.setText("Ladrão");
        thief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thiefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(paladin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mage, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(warrior, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thief)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paladin)
                    .addComponent(mage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warrior)
                    .addComponent(thief))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paladinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paladinActionPerformed
        this.player.addHero(new Paladin());
    }//GEN-LAST:event_paladinActionPerformed

    private void mageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mageActionPerformed
        this.player.addHero(new Mage());
    }//GEN-LAST:event_mageActionPerformed

    private void warriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warriorActionPerformed
        this.player.addHero(new Warrior());
    }//GEN-LAST:event_warriorActionPerformed

    private void thiefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thiefActionPerformed
        this.player.addHero(new Thief());
    }//GEN-LAST:event_thiefActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mage;
    private javax.swing.JButton paladin;
    private javax.swing.JButton thief;
    private javax.swing.JButton warrior;
    // End of variables declaration//GEN-END:variables
}
