/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import core.Game;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import mappings.base.Player;

/**
 *
 * @author 11518681
 */
public class PlayerCreationScreen extends javax.swing.JFrame {

    /**
     * Creates new form playerCreationScreen
     */
    public PlayerCreationScreen() {
        this.initComponents();
        setSize(638, 349);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        amountOfPlayers = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dark Poower");
        setBackground(new java.awt.Color(0, 0, 51));
        setForeground(new java.awt.Color(0, 0, 51));
        setSize(new java.awt.Dimension(913, 471));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(397, 215, 150, 23);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(88, 215, 140, 23);

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de usuários que irão jogar: ");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(92, 122, 172, 14);
        jPanel2.add(amountOfPlayers);
        amountOfPlayers.setBounds(306, 118, 241, 20);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.PNG"))); // NOI18N
        jPanel2.add(jLabelImage);
        jLabelImage.setBounds(0, 0, 630, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Player> players = new ArrayList();
        try {
            int i = Integer.parseInt(this.amountOfPlayers.getText());
            if (i < 2) {
                JOptionPane.showMessageDialog(this, "Quantidade de jogadores deve ser maior que 2!");
            } else {
                while(i > 0) {
                    String name = JOptionPane.showInputDialog("Digite o nome do usuario " + i);
                    if (name != null && !name.equals("")) {
                        players.add(new Player(name));
                        i--;
                    } else {
                        return;
                    }
                    
                }
                Game g = new Game(players);
                SelectHeroesScreen selectHeroes = new SelectHeroesScreen(g);
                selectHeroes.setVisible(true);
                this.dispose();                        
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantidade de jogadores deve ser um numero!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HomeScreen home = new HomeScreen();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountOfPlayers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


}
