/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import core.Game;
import javax.swing.JOptionPane;
import mappings.base.Hero;
import mappings.base.Player;
import mappings.humans.Mage;
import mappings.humans.Paladin;
import mappings.humans.Thief;
import mappings.humans.Warrior;
import mappings.inhumans.Animal;
import mappings.inhumans.Dragon;
import mappings.inhumans.Troll;
import mappings.inhumans.Zombie;

/**
 *
 * @author mresende
 */
public class SelectHeroesScreen extends javax.swing.JFrame {

    private final Player player;
    private Game game;

    public SelectHeroesScreen(Game game) {
        initComponents();
       setSize(850, 393);
        this.player = game.getCurrentPlayer();
        this.game = game;
        this.nameLabel.setText(this.player.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        hero2Class = new javax.swing.JComboBox<>();
        hero1Class = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(0, 102, 102));

        hero2Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Mago", "Paladino", "Ladrao", "Guerreiro", "Animal", "Dragao", "Troll", "Zumbi" }));

        hero1Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Mago", "Paladino", "Ladrao", "Guerreiro", "Animal", "Dragao", "Troll", "Zumbi" }));

        jButton2.setText("Concluido");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione o heroi principal");

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("jLabel1");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecione o heroi secundario");

        jLayeredPane1.setLayer(hero2Class, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hero1Class, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(nameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(nameLabel)))
                .addContainerGap(467, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(434, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hero1Class, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hero2Class, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(203, 203, 203))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addContainerGap()))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nameLabel)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(hero1Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                    .addComponent(hero2Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)
                    .addComponent(jButton2)
                    .addContainerGap()))
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 842, 354);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(2129, 770, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String clazz1 = this.hero1Class.getSelectedItem().toString();
        String clazz2 = this.hero2Class.getSelectedItem().toString();
        Hero h1 = this.getSelectedHero(clazz1);
        Hero h2 = this.getSelectedHero(clazz2);
        if (h1 != null && h2 != null) {
            this.player.addHero(h1);
            this.player.addHero(h2);
            if (this.player.isReady()) {
                if (this.game.playersHaveEnoughHeroes()) {
                    BattleScreen battle = new BattleScreen(this.game.getCurrentPlayer(), this.game, this.game.getCurrentPlayer().getActiveHero());
                    battle.setVisible(true);
                } else {
                    this.game.setCurrentPlayer(this.game.getNextPlayer());
                    SelectHeroesScreen selectHeroes = new SelectHeroesScreen(this.game);
                    selectHeroes.setVisible(true);
                }
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione dois herois validos!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private Hero getSelectedHero(String className) {

        switch (className) {
            case "Guerreiro":
                return new Warrior();
            case "Mago":
                return new Mage();
            case "Paladino":
                return new Paladin();
            case "Ladrao":
                return new Thief();
            case "Animal":
                return new Animal();
            case "Dragao":
                return new Dragon();
            case "Troll":
                return new Troll();
            case "Zumbi":
                return new Zombie();
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hero1Class;
    private javax.swing.JComboBox<String> hero2Class;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
