/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import core.Game;
import javax.swing.JOptionPane;
import mappings.base.Hero;
import mappings.base.Player;
import mappings.humans.Mage;
import mappings.humans.Paladin;
import mappings.humans.Thief;
import mappings.humans.Warrior;
import mappings.inhumans.Animal;
import mappings.inhumans.Dragon;
import mappings.inhumans.Troll;
import mappings.inhumans.Zombie;

/**
 *
 * @author mresende
 */
public class SelectHeroesScreen extends javax.swing.JFrame {

    private final Player player;
    private Game game;

    public SelectHeroesScreen(Game game) {
        initComponents();
        this.player = game.getCurrentPlayer();
        this.game = game;
        this.nameLabel.setText(this.player.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        hero1Class = new javax.swing.JComboBox<>();
        hero2Class = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("jLabel1");

        jLabel2.setText("Selecione o heroi principal");

        jLabel3.setText("Selecione o heroi secundario");

        jButton2.setText("Concluido");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hero1Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Mago", "Paladino", "Ladrao", "Guerreiro", "Animal", "Dragao", "Troll", "Zumbi" }));

        hero2Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Mago", "Paladino", "Ladrao", "Guerreiro", "Animal", "Dragao", "Troll", "Zumbi" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(667, 667, 667)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(573, 573, 573)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hero1Class, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero2Class, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(nameLabel)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hero1Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hero2Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String clazz1 = this.hero1Class.getSelectedItem().toString();
        String clazz2 = this.hero2Class.getSelectedItem().toString();
        Hero h1 = this.getSelectedHero(clazz1);
        Hero h2 = this.getSelectedHero(clazz2);
        if (h1 != null && h2 != null) {
            this.player.addHero(h1);
            this.player.addHero(h2);
            if (this.player.isReady()) {
                if (this.game.playersHaveEnoughHeroes()) {
                    BattleScreen battle = new BattleScreen(this.game.getCurrentPlayer(), this.game, this.game.getCurrentPlayer().getActiveHero());
                    battle.setVisible(true);
                } else {
                    this.game.setCurrentPlayer(this.game.getNextPlayer());
                    SelectHeroesScreen selectHeroes = new SelectHeroesScreen(this.game);
                    selectHeroes.setVisible(true);
                }
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione dois herois validos!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private Hero getSelectedHero(String className) {

        switch (className) {
            case "Guerreiro":
                return new Warrior();
            case "Mago":
                return new Mage();
            case "Paladino":
                return new Paladin();
            case "Ladrao":
                return new Thief();
            case "Animal":
                return new Animal();
            case "Dragao":
                return new Dragon();
            case "Troll":
                return new Troll();
            case "Zumbi":
                return new Zombie();
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hero1Class;
    private javax.swing.JComboBox<String> hero2Class;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
